import { Award, FolderPlus, ImagePlus, Plus, UserRoundPen } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import LoadingState from "../../components/ui/LoadingState";
import { getDashboardData } from "../../services/adminService";

export default function Dashboard() {
  const [state, setState] = useState({ data: null, loading: true, error: "" });
  useEffect(() => { getDashboardData().then((data) => setState({ data, loading: false, error: "" })).catch((error) => setState({ data: null, loading: false, error: error.message })); }, []);
  if (state.loading) return <LoadingState label="Loading dashboard" />;
  if (state.error) return <p role="alert" className="field-error">{state.error}</p>;
  const metrics = [["Total projects", state.data.totalProjects], ["Published", state.data.publishedProjects], ["Drafts", state.data.draftProjects], ["Featured", state.data.featuredProjects], ["Published proofs", state.data.publishedProofs]];
  return <><div className="breadcrumbs"><span>Admin</span><span>/</span><span>Dashboard</span></div><header className="admin-page-header"><div><h1>Dashboard</h1><p>Manage the content that appears across your portfolio.</p></div><Link to="/admin/projects/new" className="btn-primary"><FolderPlus size={17} /> Add project</Link></header><div className="metric-grid">{metrics.map(([label, value]) => <div className="metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="mt-4 text-xs text-muted">Last updated: {state.data.lastUpdated ? new Date(state.data.lastUpdated).toLocaleString() : "No content yet"}</p>
    <section className="dashboard-certificates"><div className="dashboard-section-heading"><div><span className="section-kicker">Credentials</span><h2>Certificate overview</h2></div><Link className="btn-secondary" to="/admin/certificates/new"><Plus size={16} /> Add certificate</Link></div><div className="certificate-metric-row"><div><strong>{state.data.totalCertificates}</strong><span>Total</span></div><div><strong>{state.data.publishedCertificates}</strong><span>Published</span></div><div><strong>{state.data.draftCertificates}</strong><span>Drafts</span></div><div><strong>{state.data.featuredCertificates}</strong><span>Featured</span></div></div>{state.data.recentCertificates.length ? <div className="recent-certificate-list"><h3>Recently updated</h3>{state.data.recentCertificates.map((certificate) => <Link to={`/admin/certificates/${certificate.databaseId}/edit`} key={certificate.databaseId}><Award size={18} aria-hidden="true" /><span><strong>{certificate.title}</strong><small>{certificate.issuer}</small></span><time dateTime={certificate.updatedAt}>{new Date(certificate.updatedAt).toLocaleDateString()}</time></Link>)}</div> : <p className="dashboard-empty-copy">No certificates have been added yet.</p>}</section>
    <div className="quick-actions"><Link className="quick-action" to="/admin/projects/new"><FolderPlus size={22} /><div><strong>Add a project</strong><span className="block">Create and publish a new case study.</span></div></Link><Link className="quick-action" to="/admin/certificates/new"><Award size={22} /><div><strong>Add a certificate</strong><span className="block">Publish a reviewed learning credential.</span></div></Link><Link className="quick-action" to="/admin/profile"><UserRoundPen size={22} /><div><strong>Edit biography</strong><span className="block">Update your public profile and availability.</span></div></Link><Link className="quick-action" to="/admin/payment-proofs"><ImagePlus size={22} /><div><strong>Add payment proof</strong><span className="block">Upload a reviewed, privacy-safe record.</span></div></Link></div></>;
}
