import { ArrowLeft, Upload } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import FormField from "../../components/ui/FormField";
import LoadingState from "../../components/ui/LoadingState";
import { useToast } from "../../contexts/ToastContext";
import { useSiteData } from "../../contexts/SiteDataContext";
import { getAdminProject, saveProject, uploadFile } from "../../services/adminService";

const emptyProject = { databaseId: null, slug: "", title: "", subtitle: "", description: "", longDescription: "", problem: "", purpose: "", imagePath: "", imageAlt: "", tags: [], category: "", status: "In Development", features: [], stack: { frontend: [], backend: [], database: [] }, github: "", demo: "", featured: false, published: false, displayOrder: 0, screenshots: [] };
const toLines = (value) => value.join("\n");
const fromLines = (value) => value.split(/[\n,]/).map((item) => item.trim()).filter(Boolean);
const validUrl = (value) => !value || /^https:\/\//i.test(value);

export default function ProjectForm() {
  const { id } = useParams();
  const editing = Boolean(id);
  const [project, setProject] = useState(emptyProject);
  const [lists, setLists] = useState({ tags: "", features: "", frontend: "", backend: "", database: "" });
  const [loading, setLoading] = useState(editing);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [screenshotAlt, setScreenshotAlt] = useState("");
  const [errors, setErrors] = useState({});
  const { notify } = useToast();
  const { refresh } = useSiteData();
  const navigate = useNavigate();
  useEffect(() => { if (!editing) return; getAdminProject(id).then((data) => { setProject(data); setLists({ tags: toLines(data.tags), features: toLines(data.features), frontend: toLines(data.stack.frontend), backend: toLines(data.stack.backend), database: toLines(data.stack.database) }); setLoading(false); }).catch((error) => { notify(error.message, "error"); setLoading(false); }); }, [editing, id, notify]);
  const parsedProject = useMemo(() => ({ ...project, tags: fromLines(lists.tags), features: fromLines(lists.features), stack: { frontend: fromLines(lists.frontend), backend: fromLines(lists.backend), database: fromLines(lists.database) } }), [lists, project]);
  const set = (key, value) => setProject((current) => ({ ...current, [key]: value }));
  const validate = () => { const next = {}; if (!project.title.trim()) next.title = "Title is required."; if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(project.slug)) next.slug = "Use lowercase letters, numbers, and hyphens."; if (!project.description.trim()) next.description = "Short description is required."; if (!project.longDescription.trim()) next.longDescription = "Full description is required."; if (!project.imageAlt.trim()) next.imageAlt = "Image alt text is required."; if (!validUrl(project.github)) next.github = "Use a secure https:// URL."; if (!validUrl(project.demo)) next.demo = "Use a secure https:// URL."; setErrors(next); return !Object.keys(next).length; };
  const submit = async (event) => { event.preventDefault(); if (!validate()) return; setSaving(true); try { const saved = await saveProject(parsedProject); await refresh(); notify(`${saved.title} saved.`); navigate("/admin/projects"); } catch (error) { notify(error.message, "error"); setSaving(false); } };
  const uploadCover = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { const path = await uploadFile("project-images", file, project.slug || "projects", { image: true }); set("imagePath", path); notify("Cover image uploaded."); } catch (error) { notify(error.message, "error"); } finally { setUploading(false); event.target.value = ""; } };
  const uploadScreenshot = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!screenshotAlt.trim()) { notify("Add screenshot alt text before uploading.", "error"); event.target.value = ""; return; }
    setUploading(true);
    try {
      const path = await uploadFile("project-images", file, `${project.slug || "projects"}/screenshots`, { image: true });
      set("screenshots", [...project.screenshots, { path, alt: screenshotAlt.trim() }]);
      setScreenshotAlt("");
      notify("Screenshot uploaded.");
    } catch (error) { notify(error.message, "error"); }
    finally { setUploading(false); event.target.value = ""; }
  };
  if (loading) return <LoadingState label="Loading project" />;
  return <><div className="breadcrumbs"><span>Admin</span><span>/</span><Link to="/admin/projects">Projects</Link><span>/</span><span>{editing ? "Edit" : "New"}</span></div><header className="admin-page-header"><div><h1>{editing ? `Edit ${project.title}` : "New project"}</h1><p>Required fields are marked with an asterisk.</p></div><Link className="btn-secondary" to="/admin/projects"><ArrowLeft size={17} /> Back</Link></header>
    <form className="admin-form" onSubmit={submit} noValidate>
      <section className="form-section"><div className="form-section-header"><h2>Project basics</h2><p>The information visitors see in project cards and the case-study header.</p></div><div className="form-section-body"><FormField label="Title" htmlFor="title" required error={errors.title}><input id="title" value={project.title} onChange={(e) => set("title", e.target.value)} aria-invalid={Boolean(errors.title)} /></FormField><FormField label="Slug" htmlFor="slug" required error={errors.slug} hint="Example: petron-inventory"><input id="slug" value={project.slug} onChange={(e) => set("slug", e.target.value.toLowerCase().replace(/\s+/g, "-"))} /></FormField><FormField label="Subtitle" htmlFor="subtitle"><input id="subtitle" value={project.subtitle || ""} onChange={(e) => set("subtitle", e.target.value)} /></FormField><FormField label="Category" htmlFor="category"><input id="category" value={project.category || ""} onChange={(e) => set("category", e.target.value)} /></FormField><FormField label="Short description" htmlFor="description" required error={errors.description}><textarea id="description" rows="3" value={project.description} onChange={(e) => set("description", e.target.value)} /></FormField><FormField label="Full case-study description" htmlFor="long-description" required error={errors.longDescription}><textarea id="long-description" rows="5" value={project.longDescription} onChange={(e) => set("longDescription", e.target.value)} /></FormField><FormField label="Problem" htmlFor="problem"><textarea id="problem" rows="3" value={project.problem || ""} onChange={(e) => set("problem", e.target.value)} /></FormField><FormField label="Purpose" htmlFor="purpose"><textarea id="purpose" rows="3" value={project.purpose || ""} onChange={(e) => set("purpose", e.target.value)} /></FormField></div></section>
      <section className="form-section"><div className="form-section-header"><h2>Media and links</h2><p>Use descriptive alternative text and secure external URLs.</p></div><div className="form-section-body"><FormField label="Cover image" htmlFor="cover" hint={project.imagePath ? `Stored as ${project.imagePath}` : "JPG, PNG, WebP, or GIF; maximum 5 MB."}><label className="btn-secondary cursor-pointer" htmlFor="cover"><Upload size={17} /> {uploading ? "Uploading…" : "Upload image"}</label><input className="sr-only" id="cover" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadCover} disabled={uploading} /></FormField><FormField label="Cover image alt text" htmlFor="image-alt" required error={errors.imageAlt}><input id="image-alt" value={project.imageAlt || ""} onChange={(e) => set("imageAlt", e.target.value)} /></FormField><FormField label="GitHub URL" htmlFor="github" error={errors.github}><input id="github" type="url" value={project.github || ""} onChange={(e) => set("github", e.target.value)} placeholder="https://github.com/…" /></FormField><FormField label="Live demo URL" htmlFor="demo" error={errors.demo}><input id="demo" type="url" value={project.demo || ""} onChange={(e) => set("demo", e.target.value)} placeholder="https://…" /></FormField></div></section>
      <section className="form-section"><div className="form-section-header"><h2>Case-study screenshots</h2><p>Upload optional supporting screens with useful alternative text.</p></div><div className="form-section-body"><FormField label="Screenshot alt text" htmlFor="screenshot-alt" hint="Describe what is visible and relevant."><input id="screenshot-alt" value={screenshotAlt} onChange={(event) => setScreenshotAlt(event.target.value)} /></FormField><FormField label="Screenshot file" htmlFor="screenshot-file"><label className="btn-secondary cursor-pointer" htmlFor="screenshot-file"><Upload size={17} /> {uploading ? "Uploading…" : "Upload screenshot"}</label><input className="sr-only" id="screenshot-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadScreenshot} disabled={uploading} /></FormField>{project.screenshots.map((screenshot, index) => <div className="form-span flex items-center justify-between gap-3 rounded-lg border border-line p-3 text-sm" key={screenshot.path || screenshot.url}><span className="min-w-0 break-words">{screenshot.alt}</span><button type="button" className="btn-ghost" onClick={() => set("screenshots", project.screenshots.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}</div></section>
      <section className="form-section"><div className="form-section-header"><h2>Features and stack</h2><p>Enter one item per line. Commas are also accepted.</p></div><div className="form-section-body"><FormField label="Technologies" htmlFor="tags"><textarea id="tags" value={lists.tags} onChange={(e) => setLists({ ...lists, tags: e.target.value })} /></FormField><FormField label="Key features" htmlFor="features"><textarea id="features" value={lists.features} onChange={(e) => setLists({ ...lists, features: e.target.value })} /></FormField><FormField label="Frontend stack" htmlFor="frontend"><textarea id="frontend" value={lists.frontend} onChange={(e) => setLists({ ...lists, frontend: e.target.value })} /></FormField><FormField label="Backend stack" htmlFor="backend"><textarea id="backend" value={lists.backend} onChange={(e) => setLists({ ...lists, backend: e.target.value })} /></FormField><FormField label="Database stack" htmlFor="database"><textarea id="database" value={lists.database} onChange={(e) => setLists({ ...lists, database: e.target.value })} /></FormField></div></section>
      <section className="form-section"><div className="form-section-header"><h2>Publishing</h2></div><div className="form-section-body"><FormField label="Project status" htmlFor="status"><input id="status" value={project.status} onChange={(e) => set("status", e.target.value)} /></FormField><FormField label="Display order" htmlFor="display-order"><input id="display-order" type="number" min="0" value={project.displayOrder} onChange={(e) => set("displayOrder", e.target.value)} /></FormField><label className="checkbox-row"><input type="checkbox" checked={project.featured} onChange={(e) => set("featured", e.target.checked)} /> Featured project</label><label className="checkbox-row"><input type="checkbox" checked={project.published} onChange={(e) => set("published", e.target.checked)} /> Published publicly</label></div></section>
      <div className="form-actions"><Link className="btn-secondary" to="/admin/projects">Cancel</Link><button className="btn-primary" type="submit" disabled={saving}>{saving ? "Saving…" : "Save project"}</button></div>
    </form></>;
}
